// Ragg Event Data
export const raggEventData = [
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "New York Philharmonic - Yunchan Lim Plays Rachmaninoff",
		eventLocation: "David Geffen Hall • New York, NY",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall2",
				totalTicket: 4,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				seatSection: "LeftSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "110 MEZZ",
				totalTicket: 4,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				seatSection: "110 MEZZ",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "New York Philharmonic - Yunchan Lim Plays Rachmaninoff",
		eventLocation: "David Geffen Hall • New York, NY",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "110 MEZZ",
				totalTicket: 4,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				seatSection: "115 MEZZ",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "210 MEZZ",
				totalTicket: 4,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				seatSection: "110 MEZZ",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "125 MEZZ",
				totalTicket: 4,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "New York Philharmonic - Yunchan Lim Plays Rachmaninoff",
		eventLocation: "David Geffen Hall • New York, NY",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2 MZ",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "New York Philharmonic - Yunchan Lim Plays Rachmaninoff",
		eventLocation: "David Geffen Hall • New York, NY",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "25",
		eventName: "Nashville Symphony - Nashville",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $60",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const rockEventData = [
	{
		dateMonth: "APR",
		dateDay: "28",
		eventName: "Goth Babe",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const salsaEventData = [
	{
		dateMonth: "APR",
		dateDay: "28",
		eventName: "Goth Babe",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "29",
		eventName: "New York Philharmonic",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Goth Babe",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $70",
		eventListingData: [
			{
				totalTicket: 4,
				amazing: true,
				name: "PE, Row 2",
				location: "Great Palace",
				price: 96,
			},

			{
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const TheatreEventData = [
	{
		dateMonth: "APR",
		dateDay: "28",
		eventName: "Hadestown - Seattle",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "29",
		eventName: "The Book of Mormon - Denver",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Hadestown - Seattle",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "29",
		eventName: "The Book of Mormon - Denver",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Hadestown - Seattle",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

// Festival Event Data
export const FestivalEventData = [
	{
		dateMonth: "APR",
		dateDay: "18",
		eventName: "Welcome to Rockville - (Friday Pass) with Avenged Sevenfold, Evanescence, Hardy",
		eventLocation: "Black Sheep, Colorado Springs, CO",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "9",
		eventName: "Rock Force - Tribute to the Iconic Rock of the 80s",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "10",
		eventName: "Madaraka Festival with Sauti Sol (16+)",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "The Book of Mormon - Denver",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Madaraka Festival with Sauti Sol (16+)",
		eventLocation: "Red Rocks Amphitheatre • Morrison, CO",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

// Sport Events
export const baseballGameEventData = [
	{
		dateMonth: "APR",
		dateDay: "18",
		eventName: "MLB Futures and Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "9",
		eventName: "MLB Futures ",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "10",
		eventName: " Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "MLB Futures and Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "MLB Futures and Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "MLB Futures and Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "MLB Futures and Legends Game",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const wweGameEventData = [
	{
		dateMonth: "APR",
		dateDay: "18",
		eventName: "WWE Raw",
		eventLocation: "VyStar Veterans Memorial Arena • Jacksonville, FL",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "9",
		eventName: "WWE Monday Night RAW ",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "10",
		eventName: " WWE Monday Night RAW",
		eventLocation: "VyStar Veterans Memorial Arena • Jacksonville, FL",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const soccerGameEventData = [
	{
		dateMonth: "APR",
		dateDay: "18",
		eventName: "Chicago Red Stars at Racing Louisville FC",
		eventLocation: "Lynn Family Stadium • Louisville, KY",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "9",
		eventName: "Valour FC at Forge FC ",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "10",
		eventName: " Chicago Red Stars at Racing Louisville FC",
		eventLocation: "Lynn Family Stadium • Louisville, KY",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "Valour FC at Forge FC",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Chicago Red Stars at Racing Louisville FC",
		eventLocation: "Lynn Family Stadium • Louisville, KY",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "Valour FC at Forge FC",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Chicago Red Stars at Racing Louisville FC",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];

export const basketballGameEventData = [
	{
		dateMonth: "APR",
		dateDay: "18",
		eventName: "Capitanes VS Indios",
		eventLocation: "Coliseo Manuel Petaca Iguina",
		eventPrice: "From $80",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "9",
		eventName: "Piratas VS Leones",
		eventLocation: "Coliseo Manuel Petaca Iguina",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "10",
		eventName: "CHAR VS MAN",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "SCE VS BAY",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "SCE VS BAY",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "19",
		eventName: "Piratas VS Leones",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $90",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
	{
		dateMonth: "APR",
		dateDay: "20",
		eventName: "Piratas VS Leones",
		eventLocation: "T-Mobile Park • Seattle, WA",
		eventPrice: "From $70",
		eventListingData: [
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: false,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "LeftSmall1",
				totalTicket: 2,
				amazing: true,
				name: "GE, Row 2",
				location: "Great Palace",
				price: 56,
			},
			{
				seatSection: "RightSmall1",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall5",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "BottomSmall3",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall2",
				totalTicket: 1,
				amazing: false,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
			{
				seatSection: "RightSmall3",
				totalTicket: 1,
				amazing: true,
				name: "ER, Row, 3",
				location: "Great Palace",
				price: 96,
			},
		],
	},
];
